### ISSUE TITLE
Feature request - Descending ilvl sorting

### ISSUE THREAD

**Issue by Deop** [Krealle/BetterBags_BetterSort#1]
Is it possible to add descending ilvl sorting for gear? So high ilvl gear would be first when sorting by ilvl

**Comment by Krealle** [comment]
Hey! It is, but won't have the time to do a proper implementation for a while.

In the meantime you can change this line in `ItemLevelSorting.lua`

`return aData.itemInfo.currentItemLevel < bData.itemInfo.currentItemLevel`

To 

`return aData.itemInfo.currentItemLevel > bData.itemInfo.currentItemLevel`

And you will get that functionality.

**Comment by Deop** [comment]
That worked, thanks.

**Comment by Krealle** [comment]
I finally got around to this, new option for it implemented in upcoming release!
