### ISSUE TITLE
[SoD] Sort bags removes arrows from quiver and places them into Backpack

### ISSUE THREAD

**Issue by perks** [Krealle/BetterBags_BetterSort#2]
Picture before sort and after sort:

![image](https://github.com/Krealle/BetterBags_BetterSort/assets/1820298/d404e596-e0c0-4fb1-aec9-c26397e0cd81)

![image](https://github.com/Krealle/BetterBags_BetterSort/assets/1820298/d4ac90ae-ae9e-47f9-9724-9d80318c384f)

Note that the arrow in question is: https://www.wowhead.com/classic/item=223648/dream-imbued-arrow , which is a SoD only item that may be affecting the sorting logic

**Comment by Krealle** [comment]
Is the problem that the items are being moved from one bag to another? If so, that is beyond the scope of what this addon does.

Does this only happen with it enabled? If so, have you tried to disable `Sort by Item Level`?
