### ISSUE TITLE
Doesn't work after recent BB update

### ISSUE THREAD

**Issue by juntereiner** [Krealle/BetterBags_BetterSort#3]
Hi,

It seems this plugin doesn't work anymore with no LUA errors.

**Comment by Krealle** [comment]
It's still working for me - I haven't bumped the version to 11.0 yet, so maybe you just don't have "Load out of Date AddOns" enabled.

**Comment by juntereiner** [comment]
I mean the last BetterBags update 0.1.80, not wow update.

Edit: nevermind i'm dumb, i used an old addon manager, it showed bettersort loaded but it wasn't.
