### ISSUE TITLE
WotLK bug..

### ISSUE THREAD

**Issue by xuxianhe** [Krealle/BetterBags_BetterSort#4]
5x ...ceBetterBags_BetterSort/AlphabeticalSort.lua:13: attempt to call field 'SortSectionsByPriority' (a nil value)
[string "@BetterBags_BetterSort/AlphabeticalSort.lua"]:13: in function <...ceBetterBags_BetterSort/AlphabeticalSort.lua:12>
[string "=[C]"]: in function `sort'
[string "@BetterBags/frames/grid.lua"]:139: in function `Sort'
[string "@BetterBags/views/gridview.lua"]:217: in function `Render'
[string "@BetterBags/frames/bag.lua"]:217: in function `Draw'
[string "@BetterBags/core/init.lua"]:198: in function `cb'
[string "@BetterBags/core/events.lua"]:45: in function <BetterBags/core/events.lua:40>
[string "=[C]"]: ?
[string "@!mMT_MediaPack/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ack/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@!mMT_MediaPack/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BetterBags/core/events.lua"]:148: in function <BetterBags/core/events.lua:147>

Locals:
kind = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 frame = Frame {
 }
 content = <table> {
 }
}
a = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 frame = Frame {
 }
 content = <table> {
 }
}
b = nil
(*temporary) = nil
(*temporary) = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 frame = Frame {
 }
 content = <table> {
 }
}
(*temporary) = <table> {
 view = 2
 headerDisabled = false
 title = Button {
 }
 fillWidth = false
 frame = Frame {
 }
 content = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call field 'SortSectionsByPriority' (a nil value)"
sort = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 baseName = "BetterBags"
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 Enable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 SortItemsByAlphaThenQuality = <function> defined @BetterBags/util/sort.lua:143
 EnableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 SortItemsByQualityThenAlpha = <function> defined @BetterBags/util/sort.lua:125
 defaultModuleLibraries = <table> {
 }
 SetDefaultModuleState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 SortSectionsBySizeDescending = <function> defined @BetterBags/util/sort.lua:87
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 SortSectionsAlphabetically = <function> defined @BetterBags_BetterSort/AlphabeticalSort.lua:12
 enabledState = false
 GetItemSortFunction = <function> defined @BetterBags_BetterSort/ItemLevelSorting.lua:17
 GetSectionSortFunction = <function> defined @BetterBags/util/sort.lua:39
 moduleName = "Sort"
 GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 defaultModuleState = true
 Disable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 IterateModules = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:433
 name = "BetterBags_Sort"
 GetItemSortBySlot = <function> defined @BetterBags/util/sort.lua:161
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 SortSectionsBySizeAscending = <function> defined @BetterBags/util/sort.lua:106
 DisableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
}
L = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 data = <table> {
 }
 EnableModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 IsModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 defaultModuleLibraries = <table> {
 }
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 baseName = "BetterBags"
 enabledState = true
 S = <function> defined @BetterBags/core/localization.lua:26
 G = <function> defined @AddO

**Comment by Krealle** [comment]
Hello, weird error! 
Pushed an update that will default to using original BetterBags function when that error occurs. 

If it continues to be a problem, then it should be an issue with BetterBags itself.

**Comment by xuxianhe** [comment]
I'll try, thanks.
